# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upNGAKfehB3QXew5lKQ5m-dXHblZOp8J
"""

print("===== CALCULADORA SIMPLES =====")

while True:
    # 1. Recebe dois números do usuário
    numero1 = float(input("Digite o primeiro número: "))
    numero2 = float(input("Digite o segundo número: "))

    # 2. Exibe o menu de operações disponíveis
    print("\nEscolha a operação desejada:")
    print("1 - Adição (+)")
    print("2 - Subtração (-)")
    print("3 - Multiplicação (*)")
    print("4 - Divisão (/)")

    # 3. Recebe a escolha do usuário
    opcao = input("Digite o número da operação (1/2/3/4): ")

    # 4. Executa a operação com base na escolha
    if opcao == '1':
        resultado = numero1 + numero2
        print(f"Resultado: {numero1} + {numero2} = {resultado}")
    elif opcao == '2':
        resultado = numero1 - numero2
        print(f"Resultado: {numero1} - {numero2} = {resultado}")
    elif opcao == '3':
        resultado = numero1 * numero2
        print(f"Resultado: {numero1} * {numero2} = {resultado}")
    elif opcao == '4':
        if numero2 != 0:
            resultado = numero1 / numero2
            print(f"Resultado: {numero1} / {numero2} = {resultado}")
        else:
            print("Erro: não é possível dividir por zero.")
    else:
        print("Opção inválida. Por favor, escolha 1, 2, 3 ou 4.")

    # 5. Pergunta se o usuário deseja continuar
    repetir = input("\nDeseja fazer outra operação? (s para sim / qualquer outra tecla para sair): ").lower()
    if repetir != 's':
        print("\nObrigado por usar a calculadora! Até a próxima.")
        break